version: "3.9"

services:
  library-api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: library_mern_nginx
    volumes: 
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      NODE_ENV: $(NODE_ENV)
      MONGO_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - library-mern-api
  mongodb:
    image: mongo   
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDE_ROOT_USERNAME: $ (MONGO_ROOT_USERMAME]
      MONGO TNTTDE ROOT PASSIORD: $(MONGO_ROOT_PASSWORD}
    volumes:

    # for persistence storage
      - mongodb-data:/data/db 
    networks:
      - library-mern-api
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTI_USERname: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes:
      - mongodo-data
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: library_mern_frontend
    volumes:
      - ./app/node_modules
      - ./client:/app
    depends_on:
      - library_api
    networks:
      - library_mern_api
  nginx:
    restart: always
    depends_on:
      - library_api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8082:8082
    networks:
      - library-mern-api
networks:
  library-mern-api:
    driver: bridge
volumes:
  mongodb-data:
    driver: local
  

